version: "3.3"

services:

  apache:

    container_name: apache_server #nombre del contenedor creado
    image: httpd #imagen a utilizar
    networks:
      nt01:
        ipv4_address: 10.0.0.100 #ip con la que se crea
    ports:
      - 80:80
    volumes:
      - configuracionweb:/usr/local/apache2/htdocs #nombre del volumen y lo que se guarda
      - configuracionapache:/usr/local/apache2/conf

  bind9:
    container_name: bind9_server
    image: internetsystemsconsortium/bind9:9.16

    networks:
      nt01:
        ipv4_address: 10.0.0.250
    ports:
      - 53:53
    volumes:
      - configuraciondns:/etc/bind
  cliente:
    container_name: apache_cliente
    image: kasmweb/desktop:1.10.0-rolling

    networks:
      nt01:
        ipv4_address: 10.0.0.200
    ports:
      - 6901:6901
    dns:
      - 10.0.0.250 
    environment:
      VNC_PW: password #el enviroment para controlar el escritorio 

volumes:
  configuracionapache:
    external: true
  configuracionweb:
    external: true #Declaración de los volumenes que son externos
  configuraciondns:
    external: true

networks:
  nt01:
    ipam:
      config:
        - subnet: 10.0.0.0/24