version: "3.3"

services:

  apache:

    container_name: apache_server
    image: httpd
    networks:
      nt01:
        ipv4_address: 10.0.0.100
    ports:
      - 80:80
    volumes:
      - configuracionweb:/usr/local/apache2/htdocs

  bind9:
    container_name: bind9_server
    image: internetsystemsconsortium/bind9:9.16

    networks:
      nt01:
        ipv4_address: 10.0.0.250
    ports:
      - 53:53
    volumes:
      - configuraciondns:/etc/bind
  cliente:
    container_name: apache_cliente
    image: kasmweb/desktop:1.10.0-rolling

    networks:
      nt01:
        ipv4_address: 10.0.0.200
    ports:
      - 6901:6901
    dns:
      - 10.0.0.250 
    environment:
      - VNC_PW= abc123.

volumes:
  configuracionweb:
    external: true
  configuraciondns:
    external: true

networks:
  nt01:
    ipam:
      config:
        - subnet: 10.0.0.0/24